server:
  port: ${SERVER_PORT}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              #lower-case-service-id: true
          
      routes:
      # skill-taxonomy service
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/tags/**
          filters:
            - StripPrefix=2

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/clusters/**
          filters:
            - StripPrefix=2

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/atoms/**
          filters:
            - StripPrefix=2

        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/capsules/**
          filters:
            - StripPrefix=2
            
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/growth-tracks/**
          filters:
            - StripPrefix=2
            
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/talent-routes/**
          filters:
            - StripPrefix=2
            
        - id: skill-service
          uri: lb://skill-service
          predicates:
            - Path=/api/v1/uploads/**
          filters:
            - StripPrefix=2
            
        # user-management service
        - id: user-management-authentication
          uri: lb://user-management
          predicates:
            - Path=/api/v1/auth/**

        - id: user-management-registration
          uri: lb://user-management
          predicates:
            - Path=/api/v1/register/**
        
        - id: user-management-roles
          uri: lb://user-management
          predicates:
            - Path=/api/v1/roles/**

        - id: user-management-profiles
          uri: lb://user-management
          predicates:
            - Path=/api/v1/users/**

      # learning management system service    
        - id: lms-service
          uri: lb://lms-service
          predicates:
            - Path=/api/v1/moodle/**
          filters:
            - StripPrefix=2  
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_URL:http://versapath-service-discovery:8761/eureka}
  instance:
    prefer-ip-address: true
