spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:true}
